# Generated by Django 4.0.3 on 2022-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymodel',
            name='fecha',
            field=models.DateField(),
        ),
    ]
